name: BNCore
main: me.pugabyte.bncore.BNCore
version: ${project.version}
softdepend: [PermissionsEx, NBTAPI, SmartInvs, Multiverse-Core, FeatherBoard, WorldGuard, WorldGuardRegionAPI, mcMMO, LiteBans, helper, Citizens, ProtocolLib, Vault, Votifier, PlaceholderAPI]
api-version: 1.15
commands:
  restoreinventory:
    description: RestoreInventory command
    aliases: restoreinv
  showenchants:
    description: ShowEnchants command
