name: BNCore
main: me.pugabyte.bncore.BNCore
version: ${project.version}
softdepend: [PermissionsEx, SmartInvs, Multiverse-Core, FeatherBoard]
api-version: 1.15
commands:
  restoreinventory:
    description: RestoreInventory command
    aliases: restoreinv
  showenchants:
    description: ShowEnchants command
