name: Nexus
main: gg.projecteden.nexus.Nexus
version: ${version}
authors:
  - GriffinCodes
  - WakkaFlocka
  - Blast-MC
  - lexikiq
api-version: 1.19
load: POSTWORLD
softdepend:
  - mcMMO
  - Multiverse-Core
  - ProtocolLib
  - WorldGuard
  - BentoBox
  - BigDoors
  - BlueMap
  - BuycraftX
  - Citizens
  - CrateAnimations
  - GlowAPI
  - HeadDatabase
  - Holograms
  - ImageOnMap
  - LibsDisguises
  - LWC
  - Multiverse-Inventories
  - NBTAPI
  - NoteBlockAPI
  - OpenInv
  - PremiumVanish
  - spark
  - Vault
  - ViaVersion
  - Votifier
