name: Nexus
main: me.pugabyte.nexus.Nexus
version: ${project.version}
api-version: 1.17
load: POSTWORLD
depend:
  - helper
  - mcMMO
  - Multiverse-Core
  - ProtocolLib
  - WorldGuard
softdepend:
  - BentoBox
  - BlueMap
  - BuycraftX
  - GlowAPI
  - HeadDatabase
  - HolographicDisplays
  - LibsDisguises
  - LWC
  - Multiverse-Inventories
  - NBTAPI
  - NoteBlockAPI
  - PremiumVanish
  - SmartInvs
  - Vault
  - ViaVersion
  - Votifier
