name: BNCore
main: me.pugabyte.bncore.BNCore
version: ${project.version}
api-version: "1.15"
softdepend:
  - PermissionsEx
  - NBTAPI
  - SmartInvs
  - Multiverse-Core
  - Multiverse-Inventories
  - FeatherBoard
  - WorldGuard
  - WorldGuardRegionAPI
  - mcMMO
  - LiteBans
  - helper
  - Citizens
  - ProtocolLib
  - Vault
  - Votifier
  - PlaceholderAPI
  - PathfinderAPI
loadbefore:
  - mcMMO
