name: BNCore
main: me.pugabyte.bncore.BNCore
version: ${project.version}
softdepend: [PermissionsEx, Minigames, Herochat, Skript, PlayerPoints]
api-version: 1.13
commands:
  alerts:
    description: Alerts command
  antibots:
    description: AntiBots command
  clearinventory:
    description: ClearInventory command
    aliases: [clean, clear, ci, clearinvent, eclean, eclear, eci, eclearinvent, eclearinventory]
  clearinventorytoggle:
    description: ClearInventoryToggle command
    aliases: [eclearinventorytoggle, clearinventoryconfirmtoggle, eclearinventoryconfirmtoggle, clearinventoryconfirmoff, eclearinventoryconfirmoff, clearconfirmoff, eclearconfirmoff, clearconfirmon, eclearconfirmon, clearconfirm, eclearconfirm]
  connect4:
    description: Connect4 command
    aliases: c4
  durabilitywarning:
    description: DurabilityWarning command
    aliases: dw
  invited:
    description: InviteRewards command
  itemeditor:
    description: ItemEditor command
  mcwiki:
    description: MinecraftWiki command
    aliases: mcw
  newminigames:
    description: Minigames command
    aliases: newmgm
  murder:
    description: Murder command
  permhelper:
    description: PermHelper command
  rainbowarmour:
    description: RainbowArmour command
    aliases: [rainbowarmor, rainbowarmour, rba]
  restoreinventory:
    description: RestoreInventory command
    aliases: restoreinv
  scoreboards:
    description: Scoreboards command
    aliases: [sb, status]
  showenchants:
    description: ShowEnchants command
  sidewayslogs:
    description: SidewaysLogs command
    aliases: swl
  sidewaysstairs:
    description: SidewaysStairs command
    aliases: sws
  stattrack:
    description: StatTrack command
  tab:
    description: Tab command
  tameables:
    description: Tameables command
  warps:
    description: Warps command
  wiki:
    description: Wiki command