name: Nexus
main: gg.projecteden.nexus.Nexus
version: ${version}
authors:
  - GriffinCodes
  - WakkaFlocka
  - Blast-MC
  - lexikiq
api-version: 1.19
load: POSTWORLD
depend:
  - helper
  - mcMMO
  - Multiverse-Core
  - ProtocolLib
  - WorldGuard
softdepend:
  - BentoBox
  - BigDoors
  - BlueMap
  - BuycraftX
  - Citizens
  - GlowAPI
  - HeadDatabase
  - HolographicDisplays
  - LibsDisguises
  - LWC
  - Multiverse-Inventories
  - NBTAPI
  - NoteBlockAPI
  - OpenInv
  - PlaceholderAPI
  - PremiumVanish
  - Spark
  - Vault
  - ViaVersion
  - Votifier
