name: BNCore
main: me.pugabyte.bncore.BNCore
version: ${project.version}
api-version: "1.15"
softdepend:
  - BuycraftX
  - Citizens
  - Essentials
  - helper
  - LiteBans
  - LWC
  - mcMMO
  - Multiverse-Core
  - Multiverse-Inventories
  - NBTAPI
  - NoteBlockAPI
  - PathfinderAPI
  - ProtocolLib
  - SmartInvs
  - Vault
  - Votifier
  - WorldGuard
  - WorldGuardRegionAPI
