name: BNCore
main: me.pugabyte.bncore.BNCore
version: ${project.version}
api-version: "1.15"
softdepend:
  - NBTAPI
  - SmartInvs
  - Multiverse-Core
  - Multiverse-Inventories
  - WorldGuard
  - WorldGuardRegionAPI
  - mcMMO
  - LiteBans
  - helper
  - Citizens
  - ProtocolLib
  - Vault
  - Votifier
  - PathfinderAPI
