package me.pugabyte.nexus.features.store.perks.emojihats;

import dev.dbassett.skullcreator.SkullCreator;
import kotlin.Pair;
import lombok.Getter;
import me.pugabyte.nexus.utils.ItemBuilder;
import me.pugabyte.nexus.utils.PacketUtils;
import me.pugabyte.nexus.utils.Tasks;
import me.pugabyte.nexus.utils.TimeUtils.Timer;
import net.minecraft.server.v1_16_R3.EnumItemSlot;
import org.bukkit.entity.Player;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import static eden.utils.StringUtils.camelCase;

public enum EmojiHat {
	CHEEKY("NWYxNWM5YjhlZGM1NjI5YjZjYWE0OTE0OGEyMGM1ODkwODUzYzI2NzQzODVlNDM4NzZjYTU2ZDFkNDY1Zg==", new ArrayList<>() {{
		add(new Pair<>("NGRiNGM4ZGZkYzc3OTJkMjRjNTMzNGE1YTJkMWQ0NjdiNmUxMGFiZmFiZDYzN2U0YTgwY2NiMDViOWNjZmJk", 15L));
		add(new Pair<>("YjdkNTMzZTY1ZjJjYWU5N2FmZTMzNGM4MWVjYzk3ZTJmYTViM2U1ZDNlY2Y4YjkxYmMzOWE1YWRiMmU3OWE=", 2L));
		add(new Pair<>("MzVhNDZmODMzNGU0OWQyNzMzODRlYjcyYjJhYzE1ZTI0YTY0MGQ3NjQ4ZTRiMjhjMzQ4ZWZjZTkzZGM5N2Fi", 8L));
		add(new Pair<>("MzAyMTEwYjRmMjkxMWMwZjU1OTc3OTZlYzgxMmU4ZmEyNjBiYTVhYjdjZmY3MjVlMTZiN2VlZTdjNjc3Yjc=", 0L));
		add(new Pair<>("NWYxNWM5YjhlZGM1NjI5YjZjYWE0OTE0OGEyMGM1ODkwODUzYzI2NzQzODVlNDM4NzZjYTU2ZDFkNDY1Zg==", 48L));
		add(new Pair<>("MzAyMTEwYjRmMjkxMWMwZjU1OTc3OTZlYzgxMmU4ZmEyNjBiYTVhYjdjZmY3MjVlMTZiN2VlZTdjNjc3Yjc=", 0L));
		add(new Pair<>("NDQ3ZGNmOWRkMjgzYWQ2ZDgzOTQyYjY2MDdhN2NlNDViZWU5Y2RmZWVmYjg0OWRhMjlkNjYxZDAzZTc5Mzg=", 0L));
		add(new Pair<>("ZGUzNTU1NTlmNGNkNTYxMThiNGJjOGI0Njk3YjYyNWUxODQ1YjYzNTc5MGMwN2JmNDkyNGM4Yzc2NzNhMmU0", 0L));
		add(new Pair<>("MjA3ZWVmOTFhNDUzYTUxNTE0ODdjOWQ2YjlkNGM0MzRkYjdmOGEwMmE0Y2FmMThlZjZmMzM1ODY3N2Y2", 0L));
		add(new Pair<>("NWYxNWM5YjhlZGM1NjI5YjZjYWE0OTE0OGEyMGM1ODkwODUzYzI2NzQzODVlNDM4NzZjYTU2ZDFkNDY1Zg==", 48L));
		add(new Pair<>("MzAyMTEwYjRmMjkxMWMwZjU1OTc3OTZlYzgxMmU4ZmEyNjBiYTVhYjdjZmY3MjVlMTZiN2VlZTdjNjc3Yjc=", 0L));
		add(new Pair<>("NDQ3ZGNmOWRkMjgzYWQ2ZDgzOTQyYjY2MDdhN2NlNDViZWU5Y2RmZWVmYjg0OWRhMjlkNjYxZDAzZTc5Mzg=", 0L));
		add(new Pair<>("ZGUzNTU1NTlmNGNkNTYxMThiNGJjOGI0Njk3YjYyNWUxODQ1YjYzNTc5MGMwN2JmNDkyNGM4Yzc2NzNhMmU0", 0L));
		add(new Pair<>("MjA3ZWVmOTFhNDUzYTUxNTE0ODdjOWQ2YjlkNGM0MzRkYjdmOGEwMmE0Y2FmMThlZjZmMzM1ODY3N2Y2", 0L));
		add(new Pair<>("NWYxNWM5YjhlZGM1NjI5YjZjYWE0OTE0OGEyMGM1ODkwODUzYzI2NzQzODVlNDM4NzZjYTU2ZDFkNDY1Zg==", 8L));
	}}),
	COOL("NDRjOGNkMzFiYWM2NTdhM2YyNmI1MmUyNjJjODNlYjgzMzhkNTY2NTFmZDIyYzE2MzM1NjVmM2RiYmM0NTc3Nw", new ArrayList<>() {{
		add(new Pair<>("ZDM2MTEwNjljMjVhZDliMzJhN2JkZjQ4NTM0OTM1YjlmNTg3NWNkODU0MDFiYzBhMDM0NjU1NjQ3MWQ0OA==", 38L));
		add(new Pair<>("ZDBmMjk0OTE4ZDlhYzlhNjViM2NmYzc1MjY2OGYzMjNmODc0ZmZhN2IxNjFlMzYxNzcyNDU5MmMxMjY1N2YxMw==", 6L));
		add(new Pair<>("MzcxYTY2MTY0ODk2ZGNkOGIxN2JmZTliYmY1ZTFlOGM0M2FmYmJkN2M3ZTQyYjc1MTQ4M2M5YzQ2OGU1Mg==", 2L));
		add(new Pair<>("NDRjOGNkMzFiYWM2NTdhM2YyNmI1MmUyNjJjODNlYjgzMzhkNTY2NTFmZDIyYzE2MzM1NjVmM2RiYmM0NTc3Nw==", 100L));
	}}),
	CRY("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", new ArrayList<>() {{
		add(new Pair<>("OWVhYmVkYTQ5NmUwNjg0ZjgwZDg4ZDRiNWE3MWQ2NWFmYWY5ZmFmMTg0ZmE0YTc3ZjgxZWQyNGM2ZGEwZjQ=", 18L));
		add(new Pair<>("MTk2YjhlMjcyYzU0YTQyMmQ5ZGYzNmQ4NWNhZmYyNjYyNGM3MzNlN2IzZjYwNDBkM2U0YzljZDZl", 6L));
		add(new Pair<>("ZGVjOWFhOWIzZjQ2MTk1YWU5YzdmZWE3YzYxMTQ4NzY0YTQxZTBkNjhkYWU0MWU4Mjg2OGQ3OTJiM2M=", 2L));
		add(new Pair<>("YmUyOWRhZGI2MGM5MDk2ZmFiOTJmZmE3NzQ5ZTMwNDYyZTE0YThhZmFmNmRlOTM4ZDljMGE0ZDc4Nzgx", 10L));
		add(new Pair<>("YzhhYmExZjQ5ZmJmODgyOTg1OWRkZDhmN2U1OTE4MTU1ZTdkZGM3ODkxOTc2OGI2ZTZjNTM2ZTUyNzhjMzE=", 2L));
		add(new Pair<>("MTA3M2JhM2YxY2ExZDFlNGY3ZTFlYzc0MmRkY2ZmOGZiMGQ5NjJiYzU2NjJkMTI3NjIyYTM3MjZlM2JiNjY=", 0L));
		add(new Pair<>("OTUyZGNkYjEzZjczMjM0MmVmMzdjYmYwOTAyOTYwOTg0OTkyZjVlNjcyODkzNzMwNTRiMDBjMmExZjc=", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 1L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 1L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
		add(new Pair<>("Mzg2NGIwOTI1YWZjMmQzMWFmNjlhZTEyNGQwNWM5Y2EzMWNlMjVmOWQyZTk3YjU2OWI5MGNhMjM2YTNl", 0L));
		add(new Pair<>("NGIwZjJmM2QzNDk5OTU5ZTk3ZDI3ZTYxMGJjZmQ5MGRiZjhkZjVlMWNmNGI5OGYyNTkyODRmMmUzNTU3Mjg=", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 1L));
		add(new Pair<>("ZmUzZTIyNzYxYzc2YjRmOGZhZDg5ZGJjODBmM2FmMjAzZTdiODIxMTIzODAxMWJlN2ZmYjgwMjYxZDljNjQ=", 0L));
		add(new Pair<>("NzMyZmUxMjFhNjNlYWFiZDk5Y2VkNmQxYWNjOTE3OTg2NTJkMWVlODA4NGQyZjkxMjdkOGEzMTVjYWQ1Y2U0", 0L));
		add(new Pair<>("ZWRlNGQ0ODVlZWMwYjA4ZTMyZmY0YTNkYjhiNzljMTUyNGNiYTkzZTQ3Zjg2MWQ4NDY4YWRmMzY3MDQ0YWI=", 0L));
	}}),
	FROWN("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", new ArrayList<>() {{
		add(new Pair<>("NGRiNGM4ZGZkYzc3OTJkMjRjNTMzNGE1YTJkMWQ0NjdiNmUxMGFiZmFiZDYzN2U0YTgwY2NiMDViOWNjZmJk", 38L));
		add(new Pair<>("YjdkNTMzZTY1ZjJjYWU5N2FmZTMzNGM4MWVjYzk3ZTJmYTViM2U1ZDNlY2Y4YjkxYmMzOWE1YWRiMmU3OWE=", 6L));
		add(new Pair<>("NmY1YzM5OTJlZDVmMjEzZGJjNmU5ZjM2ODkxNWZiNTE5ZGI0ZTE4NzQwNzUxOGRkMjVlMDE0YjgxYzZlNmVi", 2L));
		add(new Pair<>("YmI0ZjM5NTlkNzc2YTRhYTE2YzQzZGRlMTZlZTM3NzdmOTU4YjVjNjZhYzA1YzU0MmNiZTI3ZjY3ZDdiZTdjZQ==", 6L));
		add(new Pair<>("NmVhMDc5YzkzMTQxYzhjNmJhZGU2MGIxOTg3ZDQyNDczOWI0NjM2MWRiZjUxM2MwYTQ5MDNkYmE0ZTY3", 1L));
		add(new Pair<>("MWMyNjcyYWFhZTU4ZjNkMTg1MmQxOWI4NDIyY2FmNzBiMzI1ODJmOGRlM2ZjYjVjN2MyNGRhY2I3ZWJjMw==", 2L));
		add(new Pair<>("ZDU0MTk5MmQ3NjEyYTE0YmE1ODk3OGQxMmZjYjIxMmJjZmY3NzM5Nzc4NjhhYzQ5MWZlYjhmMWZhNWJj", 1L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 36L));
		add(new Pair<>("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", 0L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 36L));
		add(new Pair<>("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", 1L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 36L));
		add(new Pair<>("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", 0L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 36L));
		add(new Pair<>("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", 1L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 20L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 14L));
		add(new Pair<>("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", 0L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 20L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 14L));
		add(new Pair<>("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", 1L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 36L));
		add(new Pair<>("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", 0L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 36L));
		add(new Pair<>("ODY1ZTFmNDQ0ZmFmYjczN2MwYWJmNWJlMWJmOTdmYzI3YWRlZGFlM2ZkOTgyMjZhNDY4ZmE3MmMxZDE3NTM=", 1L));
		add(new Pair<>("OTEzZWJlZGFjNDdlNDQ4NmExOGZjNjM0MzI0ZTZhMjJiMWI5YzU2YzMyYzBmMTMzOTdhNzQ3YzZmYzQ0Yzk=", 2L));
	}}),
	GRIN("MDFiOWRlZjU1ODc2YzQxYzE3YzgxNWY4ODExNWYwMmM5NWY4OTYyMGZiZWQ2YTZjYjJkMzhkNDZmZTA1", new ArrayList<>() {{
		add(new Pair<>("NDY1YjU2MTFmOGFiYzAxZDliYjhmY2Q2MmYzYTY0YjUxMjU1MzRhNDI4NzMxZjIwMmU2MTlkOWNlMQ==", 3L));
		add(new Pair<>("YTVkNDNlYjBlYzVmNmRlMWQ0NjliNjk2ODA5NzhhNmRkNzExNzc3MmVlMGQ4MmZmZGYwODc0OWU4NGRmN2Vk", 3L));
		add(new Pair<>("OGQ4ZjVmYjM4N2NhNjZmYzJmNjViOTFmY2IyMzE2MDQ1NDhlODU2NTg5NWJiOTZjNjc2OTg0MjA1ZTZmMTk=", 28L));
		add(new Pair<>("MDFiOWRlZjU1ODc2YzQxYzE3YzgxNWY4ODExNWYwMmM5NWY4OTYyMGZiZWQ2YTZjYjJkMzhkNDZmZTA1", 117L));
	}}),
	RAGE("YTc1MDEyN2YxYzNjNzFmNmE1ZjVlOTkxN2E4MjVlOTIzNWUxOTU5YjI1OGZmMjliNmZmOTc3MWNiNDQ=", new ArrayList<>() {{
		add(new Pair<>("NTEzZjdlYjlmY2Y5OTI2YmY3Yjk0MDQ5YWVmNWVmZGI3YmJlNzBiY2M3NGYzZjY2MThlMTJkYzE4MWQ2Mjc=", 6L));
		add(new Pair<>("NDdiYmY2ZDlmNGM1NzU1NmVlZjgxNmM1MGViNzVmOWQxNThmNTM5NTQ5NTdhYWJlNmMyZTE0ZmZhNmM5MA==", 2L));
		add(new Pair<>("YTc1MDEyN2YxYzNjNzFmNmE1ZjVlOTkxN2E4MjVlOTIzNWUxOTU5YjI1OGZmMjliNmZmOTc3MWNiNDQ=", 2L));
		add(new Pair<>("ZTk1YjIwZmIxZmNmYmVmMjIyMDYyZGQ0M2VlY2JjYjM4NzFjNTI4NjY1ZjhlZDY3NWY0MmZjNmU1ODlhMGI3", 2L));
		add(new Pair<>("Mjc1YzQ2MTg0ZjlhODUzNTFkNmJhNjE4ZjhkMTY1NWNiNWI3MWQ2ZmM2ZWQzY2NjNDYyZDkxNmQzNzZhOGRi", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 1L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 1L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 1L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("N2Y4ZGI4Y2YyNDFmMjU2NWM1YmQ0OTVhMDY5NWI3Y2FjOTM3MGM4YmZkNzMyZDZkODc0ZTYyZmIxMmYzZGE=", 0L));
		add(new Pair<>("ZmExNTFjZWI2NmIzNDEyNzc1ZTlkNDQ4NzkwNDZhMzk4ZGJkYjdkZmNiMGFmNTcxYjdhMDNlNzJkOWZiZjE=", 0L));
		add(new Pair<>("YzlmOGQwNDA1Nzk3ODgxN2NiODFlMDk1Y2NjNTk3OTlmZTRiNzgwZmZkYmZiOWYwZDYyYWEyODY3MjE4NTY=", 0L));
	}}),
	SLEEPY("YTA1OGNlNjFkMWU5YWQ2YjExNWRhMWNiZGY1NmQ5N2UyYTJjYjM4ZTMxZWExNzk0MzFkOTM1NjE2MTYzNTgx", new ArrayList<>() {{
		add(new Pair<>("NGRiNGM4ZGZkYzc3OTJkMjRjNTMzNGE1YTJkMWQ0NjdiNmUxMGFiZmFiZDYzN2U0YTgwY2NiMDViOWNjZmJk", 0L));
		add(new Pair<>("NTA1YzIzNzczMWFlN2E2NGMwNjY4Y2U4ODlkYzZkMWUyMWNmZGJjYzlmYTUxZWZlNDgxNDNlZTQ1NmU0NWE5", 0L));
		add(new Pair<>("MzZmNTQ5NTk3ZmE1NmJmYjhiZTk3NGZmMmExODg3ZjQ2ODYyM2RiNzc0ZjUxY2E3NjBkZmJhMTcyODQy", 0L));
		add(new Pair<>("ODg4YTgyNjMxMTJjNGM5MzlkODJhMmRmZDNkOWI5ZTg5NjkyNWQ0MWJmZjc4NjllNTlkZjZiMTkyZDg2ZGQ3", 8L));
		add(new Pair<>("NjI2ZDk1YTBhY2I0MjI0YWY0ODE4ZGI2NzBiMzZlNWYyMDE5MmE4OWVmYjk2ZmE1YzJiZjBjN2U0M2YyZDdm", 2L));
		add(new Pair<>("NDYzMTE3MTdlOGMyZDU4ODI5NDJiOTI3OTQxN2I1MTgzMmNiMmEyZjdiMDZmODIxNWI5ZmZmZTcxZjM2MGYy", 2L));
		add(new Pair<>("ZThjOWM2ZWZhZDljZWU4ZmU3ZDNiNTYzNzBmNjY3NTkzM2RiOWZjZGYyMzZhMWM0OWI2MzQ5MjUxYTRmNWE1Ng==", 4L));
		add(new Pair<>("N2Q5ZjBmMTllZjE2MWJmYWJhZWFhNDljNTI4ODBiZWNmZTgyZmI5NjJiYmIyMTdkMTc0M2QwZjFiNTNhOTU=", 13L));
		add(new Pair<>("YTA1OGNlNjFkMWU5YWQ2YjExNWRhMWNiZGY1NmQ5N2UyYTJjYjM4ZTMxZWExNzk0MzFkOTM1NjE2MTYzNTgx", 5L));
		add(new Pair<>("N2Q5ZjBmMTllZjE2MWJmYWJhZWFhNDljNTI4ODBiZWNmZTgyZmI5NjJiYmIyMTdkMTc0M2QwZjFiNTNhOTU=", 12L));
		add(new Pair<>("YTA1OGNlNjFkMWU5YWQ2YjExNWRhMWNiZGY1NmQ5N2UyYTJjYjM4ZTMxZWExNzk0MzFkOTM1NjE2MTYzNTgx", 4L));
		add(new Pair<>("N2Q5ZjBmMTllZjE2MWJmYWJhZWFhNDljNTI4ODBiZWNmZTgyZmI5NjJiYmIyMTdkMTc0M2QwZjFiNTNhOTU=", 14L));
		add(new Pair<>("YTA1OGNlNjFkMWU5YWQ2YjExNWRhMWNiZGY1NmQ5N2UyYTJjYjM4ZTMxZWExNzk0MzFkOTM1NjE2MTYzNTgx", 3L));
		add(new Pair<>("N2Q5ZjBmMTllZjE2MWJmYWJhZWFhNDljNTI4ODBiZWNmZTgyZmI5NjJiYmIyMTdkMTc0M2QwZjFiNTNhOTU=", 13L));
		add(new Pair<>("YTA1OGNlNjFkMWU5YWQ2YjExNWRhMWNiZGY1NmQ5N2UyYTJjYjM4ZTMxZWExNzk0MzFkOTM1NjE2MTYzNTgx", 4L));
		add(new Pair<>("N2Q5ZjBmMTllZjE2MWJmYWJhZWFhNDljNTI4ODBiZWNmZTgyZmI5NjJiYmIyMTdkMTc0M2QwZjFiNTNhOTU=", 13L));
		add(new Pair<>("YTA1OGNlNjFkMWU5YWQ2YjExNWRhMWNiZGY1NmQ5N2UyYTJjYjM4ZTMxZWExNzk0MzFkOTM1NjE2MTYzNTgx", 4L));
		add(new Pair<>("N2Q5ZjBmMTllZjE2MWJmYWJhZWFhNDljNTI4ODBiZWNmZTgyZmI5NjJiYmIyMTdkMTc0M2QwZjFiNTNhOTU=", 13L));
		add(new Pair<>("YTA1OGNlNjFkMWU5YWQ2YjExNWRhMWNiZGY1NmQ5N2UyYTJjYjM4ZTMxZWExNzk0MzFkOTM1NjE2MTYzNTgx", 4L));
		add(new Pair<>("N2Q5ZjBmMTllZjE2MWJmYWJhZWFhNDljNTI4ODBiZWNmZTgyZmI5NjJiYmIyMTdkMTc0M2QwZjFiNTNhOTU=", 1L));
	}}),
	SMILE("Y2MzNWRmZTliNWJlZTFlMTM5ZDcyOGFkOGFlYWYyMzU1NmUyZTE5ZmM3NjE1Yjk5NjVjMGE5YTZlNTY2Yzg5MA==", new ArrayList<>() {{
		add(new Pair<>("YjdkNTMzZTY1ZjJjYWU5N2FmZTMzNGM4MWVjYzk3ZTJmYTViM2U1ZDNlY2Y4YjkxYmMzOWE1YWRiMmU3OWE=", 18L));
		add(new Pair<>("ZDE3ZThiYTE3NDU5ZDIwZmQ3MzY3MmJjYjhhOWUyYThhNDRjZjBhNWZmMTU0MTIyZDk2YjVkYmJkOTE3MWE=", 19L));
		add(new Pair<>("Y2MzNWRmZTliNWJlZTFlMTM5ZDcyOGFkOGFlYWYyMzU1NmUyZTE5ZmM3NjE1Yjk5NjVjMGE5YTZlNTY2Yzg5MA==", 116L));
	}}),
	SURPRISED("YjMyOGRiMWMzMjM1ODVhZGViYTE5MDdjZWQzMDYwNTBlMDJhYTc3NTkxNTg4ZmIxODJmZGVhZjQyM2FkNg==", new ArrayList<>() {{
		add(new Pair<>("MTExNWIyN2JkMWQ3OWI2ODhmOTEwNmEzZmMyMzM3NGEyNGM3ZjczZWY5ZDkzZjU2NzI2MWE0ZmVmZmQ3Mw==", 3L));
		add(new Pair<>("YjMyOGRiMWMzMjM1ODVhZGViYTE5MDdjZWQzMDYwNTBlMDJhYTc3NTkxNTg4ZmIxODJmZGVhZjQyM2FkNg==", 3L));
		add(new Pair<>("ZmRiZGUwYzQ0ZTk5ZjhkYTY0ODhhOTM1ODhhODJhYWJkNGExZmM2MDNlZDJhYWY1MWQ1NjcxYzNkNGQ=", 3L));
		add(new Pair<>("NDU4Njg1MjlmYmY0YmU2MjkzNzEyNzViMTEzOGRhYjkyOTU3NjAyMTcxNmVlNzM3ZGIxMjYzNGFhMTI1YWYz", 82L));
	}}),
	WINK("MjdmNjRlMjdiYzg1MGEzM2ZkZmZmYjc5YjU2YzliYWVhOGExOGY5NzYzYjdjYWQ1NmM0YjZhMmU5ZDM=", new ArrayList<>() {{
		add(new Pair<>("NzM3NDJkZWZiYzQ2NzdlNDU0NjhiOTMyNGQ5NzA0ZjYzNWE1ZmMzMTFlOWI4MzY4ZGQ1Y2M0Y2QyODJkNmE=", 8L));
		add(new Pair<>("Y2UyNWM1MmVlZTQ3YzEyZTFhYTE2OTg5Y2VjOWM5ZDNlNDlhZjhjNDRiNzFlYmM5NTNjYTFkMWZmMmQ1OTY3MA==", 3L));
		add(new Pair<>("MjdmNjRlMjdiYzg1MGEzM2ZkZmZmYjc5YjU2YzliYWVhOGExOGY5NzYzYjdjYWQ1NmM0YjZhMmU5ZDM=", 3L));
		add(new Pair<>("OWQ5ZWI2MGQ5MmMxZmYyZTljZWM2NWRkYzIzYzJmYjdlMTI0NTBiMzYwNzFkZGRkNjY5MGY4ODc1NDg2ZDg=", 4L));
		add(new Pair<>("MjdmNjRlMjdiYzg1MGEzM2ZkZmZmYjc5YjU2YzliYWVhOGExOGY5NzYzYjdjYWQ1NmM0YjZhMmU5ZDM=", 53L));
		add(new Pair<>("OWQ5ZWI2MGQ5MmMxZmYyZTljZWM2NWRkYzIzYzJmYjdlMTI0NTBiMzYwNzFkZGRkNjY5MGY4ODc1NDg2ZDg=", 4L));
		add(new Pair<>("MjdmNjRlMjdiYzg1MGEzM2ZkZmZmYjc5YjU2YzliYWVhOGExOGY5NzYzYjdjYWQ1NmM0YjZhMmU5ZDM=", 53L));
		add(new Pair<>("OWQ5ZWI2MGQ5MmMxZmYyZTljZWM2NWRkYzIzYzJmYjdlMTI0NTBiMzYwNzFkZGRkNjY5MGY4ODc1NDg2ZDg=", 4L));
		add(new Pair<>("MjdmNjRlMjdiYzg1MGEzM2ZkZmZmYjc5YjU2YzliYWVhOGExOGY5NzYzYjdjYWQ1NmM0YjZhMmU5ZDM=", 9L));
	}}),
	GOOFY("NzZkODg2M2RjNzljM2I0ZmJlNGNhNjE5YjVmMzU2YTRlYjVjOTczNGIzM2EyNTUyYWM5OTA1NTFiMTIxMQ==", new ArrayList<>() {{
		add(new Pair<>("YTVmMTdiNjFjMTgxZWY2ZTlmY2QzZTQxMWJlN2FhZTAzNDcyMTBiOTRlNzEyNTlhNmZkMWZjNWNkZjU4MjY=", 5L));
		add(new Pair<>("NDQzYWQ3ZDE2ZDg0MTg4MWJhZjExM2RhY2U2MGEyY2U2YzQ3M2E4MDUzNTk0OGViY2VhZDQ5OTkyYzViOTZh", 5L));
		add(new Pair<>("NzZkODg2M2RjNzljM2I0ZmJlNGNhNjE5YjVmMzU2YTRlYjVjOTczNGIzM2EyNTUyYWM5OTA1NTFiMTIxMQ==", 5L));
		add(new Pair<>("ZDFkZjUwNzU3NWM5NGFkNjNlNDBjNGQ0YTFkZDljOTk2MGY5NmFlOTJhZTM2Y2QxZWQxNmM2ZjU0NDYyNg==", 5L));
		add(new Pair<>("NzZkODg2M2RjNzljM2I0ZmJlNGNhNjE5YjVmMzU2YTRlYjVjOTczNGIzM2EyNTUyYWM5OTA1NTFiMTIxMQ==", 5L));
		add(new Pair<>("NDQzYWQ3ZDE2ZDg0MTg4MWJhZjExM2RhY2U2MGEyY2U2YzQ3M2E4MDUzNTk0OGViY2VhZDQ5OTkyYzViOTZh", 5L));
		add(new Pair<>("YTVmMTdiNjFjMTgxZWY2ZTlmY2QzZTQxMWJlN2FhZTAzNDcyMTBiOTRlNzEyNTlhNmZkMWZjNWNkZjU4MjY=", 5L));
		add(new Pair<>("NDQzYWQ3ZDE2ZDg0MTg4MWJhZjExM2RhY2U2MGEyY2U2YzQ3M2E4MDUzNTk0OGViY2VhZDQ5OTkyYzViOTZh", 5L));
		add(new Pair<>("NzZkODg2M2RjNzljM2I0ZmJlNGNhNjE5YjVmMzU2YTRlYjVjOTczNGIzM2EyNTUyYWM5OTA1NTFiMTIxMQ==", 5L));
		add(new Pair<>("ZDFkZjUwNzU3NWM5NGFkNjNlNDBjNGQ0YTFkZDljOTk2MGY5NmFlOTJhZTM2Y2QxZWQxNmM2ZjU0NDYyNg==", 5L));
		add(new Pair<>("NzZkODg2M2RjNzljM2I0ZmJlNGNhNjE5YjVmMzU2YTRlYjVjOTczNGIzM2EyNTUyYWM5OTA1NTFiMTIxMQ==", 5L));
		add(new Pair<>("NDQzYWQ3ZDE2ZDg0MTg4MWJhZjExM2RhY2U2MGEyY2U2YzQ3M2E4MDUzNTk0OGViY2VhZDQ5OTkyYzViOTZh", 5L));
		add(new Pair<>("YTVmMTdiNjFjMTgxZWY2ZTlmY2QzZTQxMWJlN2FhZTAzNDcyMTBiOTRlNzEyNTlhNmZkMWZjNWNkZjU4MjY=", 5L));
		add(new Pair<>("NDQzYWQ3ZDE2ZDg0MTg4MWJhZjExM2RhY2U2MGEyY2U2YzQ3M2E4MDUzNTk0OGViY2VhZDQ5OTkyYzViOTZh", 5L));
		add(new Pair<>("NzZkODg2M2RjNzljM2I0ZmJlNGNhNjE5YjVmMzU2YTRlYjVjOTczNGIzM2EyNTUyYWM5OTA1NTFiMTIxMQ==", 5L));
		add(new Pair<>("ZDFkZjUwNzU3NWM5NGFkNjNlNDBjNGQ0YTFkZDljOTk2MGY5NmFlOTJhZTM2Y2QxZWQxNmM2ZjU0NDYyNg==", 5L));
		add(new Pair<>("NzZkODg2M2RjNzljM2I0ZmJlNGNhNjE5YjVmMzU2YTRlYjVjOTczNGIzM2EyNTUyYWM5OTA1NTFiMTIxMQ==", 5L));
		add(new Pair<>("NDQzYWQ3ZDE2ZDg0MTg4MWJhZjExM2RhY2U2MGEyY2U2YzQ3M2E4MDUzNTk0OGViY2VhZDQ5OTkyYzViOTZh", 5L));
		add(new Pair<>("YTVmMTdiNjFjMTgxZWY2ZTlmY2QzZTQxMWJlN2FhZTAzNDcyMTBiOTRlNzEyNTlhNmZkMWZjNWNkZjU4MjY=", 5L));
		add(new Pair<>("NDQzYWQ3ZDE2ZDg0MTg4MWJhZjExM2RhY2U2MGEyY2U2YzQ3M2E4MDUzNTk0OGViY2VhZDQ5OTkyYzViOTZh", 5L));
	}}),
	LOVE("ZmQyNmFlNGI1NzkzZDA4N2U2MmEyY2YzZjM0MzU5ODI5ZDAyODY5YWFlNjYyNmJmY2ZmNTlkZTE0NjlmNTE=", new ArrayList<>() {{
		add(new Pair<>("OTAxYjk1OGVkMmMzNmU0NWJhZTcyYjQyZDRlZTcxOWQ0NTI0MGIyMzM2NjkwOTFiMWNjOWUwNzBlMzExMTk=", 39L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 2L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ZmQyNmFlNGI1NzkzZDA4N2U2MmEyY2YzZjM0MzU5ODI5ZDAyODY5YWFlNjYyNmJmY2ZmNTlkZTE0NjlmNTE=", 3L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 2L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ZmQyNmFlNGI1NzkzZDA4N2U2MmEyY2YzZjM0MzU5ODI5ZDAyODY5YWFlNjYyNmJmY2ZmNTlkZTE0NjlmNTE=", 3L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 3L));
		add(new Pair<>("OTAxYjk1OGVkMmMzNmU0NWJhZTcyYjQyZDRlZTcxOWQ0NTI0MGIyMzM2NjkwOTFiMWNjOWUwNzBlMzExMTk=", 39L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 2L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 0L));
		add(new Pair<>("ZmQyNmFlNGI1NzkzZDA4N2U2MmEyY2YzZjM0MzU5ODI5ZDAyODY5YWFlNjYyNmJmY2ZmNTlkZTE0NjlmNTE=", 4L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 2L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ZmQyNmFlNGI1NzkzZDA4N2U2MmEyY2YzZjM0MzU5ODI5ZDAyODY5YWFlNjYyNmJmY2ZmNTlkZTE0NjlmNTE=", 3L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 0L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 3L));
		add(new Pair<>("OTAxYjk1OGVkMmMzNmU0NWJhZTcyYjQyZDRlZTcxOWQ0NTI0MGIyMzM2NjkwOTFiMWNjOWUwNzBlMzExMTk=", 40L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 2L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ZmQyNmFlNGI1NzkzZDA4N2U2MmEyY2YzZjM0MzU5ODI5ZDAyODY5YWFlNjYyNmJmY2ZmNTlkZTE0NjlmNTE=", 4L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 1L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 0L));
		add(new Pair<>("ZmQyNmFlNGI1NzkzZDA4N2U2MmEyY2YzZjM0MzU5ODI5ZDAyODY5YWFlNjYyNmJmY2ZmNTlkZTE0NjlmNTE=", 4L));
		add(new Pair<>("OTZmYmI1MmE0ZDBjNjJkOGU2Y2FlOGM0ODVlNTUxYjM3ZmVjNjhlNmRhYWIyM2Q4NWYyZmY1MmZhYTRjNA==", 1L));
		add(new Pair<>("ODk1ZjY0MTViZDk0MjRhNjY0ZDY5NDM3MWE4NDY4MzhjMjBmYjM2YzNiNGEyMmYzODVmZTdlM2RjZTI5OTY=", 2L));
		add(new Pair<>("OTAxYjk1OGVkMmMzNmU0NWJhZTcyYjQyZDRlZTcxOWQ0NTI0MGIyMzM2NjkwOTFiMWNjOWUwNzBlMzExMTk=", 16L));
	}}),
	DEALWITHIT("MzkyM2Y1YjQyZDE2NzcxNTVkMDg0NDJjMGFhMzk4NTE1OTYxNTZjNWUwOWIzNDYxYWEzNTg2ODk4OWE0YmI=", new ArrayList<>() {{
		add(new Pair<>("NjVlZTY1NDEyNDVmZDViOTgyMTdjZWFmOTQxMGE0YWE5ZmJkNWFiY2ZiNjQ2ZDMzMjIyNzI5YTFkNmQxNTlm", 19L));
		add(new Pair<>("OWFhZjFkY2JjMWE4ODUzNGY0YzZhODM5NjFhZDA4NTY5Zjc1NTlkY2M5NjdiYjY0OGFjNDhlZTcwZmM0Yw==", 6L));
		add(new Pair<>("ZWJhNzE1ODk4MTIzMmE1MTIxZTk1NWVhM2YyMGUzNjExYWI4NWJkMTdiMzcyNGFjMjQ4MWRiYzBjMTkwNTQ=", 6L));
		add(new Pair<>("NTk5ZWI3NGVjMmJiMGFkZGVkMThlYmQ3NzdhNWE3NDc4ZTg2MjU2ZGViNTM2ZGNjYmZjNGFjZDliZTJhMjg=", 5L));
		add(new Pair<>("ZGUyZDgyNmRmNGNmMTY5Y2I4YmMyOGVmNGExY2U0N2IyNzNlZDU3Yzc5OTNjNDFjMjA2OWM4ZDM2Y2U0N2RmNg==", 40L));
		add(new Pair<>("NDczNGQyYjQ2YWQzM2E2ODk4Njk1MTVkMTdhODIwZjFmMjMxOWFhZDU0NTU0YjZiYTI4ZTc5ZTJjOWNlNWVi", 5L));
		add(new Pair<>("YTMyNGI1YzhmZTY5ZGZkMDYyMTg1NTg5OTYyZGE2NmUyOGE4OTk5YTc5N2MwNDA1M2FiYzFlM2ZjMWMx", 15L));
		add(new Pair<>("ZmU3OWU1ZjlkODFjOGE4NGUxZjljMmE4MTc2ODdmM2I5NTQzYmRiYjYwOWVmOGM2ZjkwOTc0ZjczZDBjMg==", 4L));
		add(new Pair<>("YmFkYTQyZGIxM2M2NTc5ODJmYTczMTg2ZGI3YjU5NDk2MTIxNzZlZGU2NzUzNjk1ZDJiNmQ5NGFhNzI2MmI3NA==", 1L));
		add(new Pair<>("MzkyM2Y1YjQyZDE2NzcxNTVkMDg0NDJjMGFhMzk4NTE1OTYxNTZjNWUwOWIzNDYxYWEzNTg2ODk4OWE0YmI=", 95L));
	}}),
	RIP("NDM5YzNkZjdhNjI4YWY4ZDc1MWVjY2ExOTc2NDJjZGMxYTA3YzMwZTMyODliMmQzMjYxZjdhNjVjZjM5NWI=", new ArrayList<>() {{
		add(new Pair<>("MzBlNzgyODVkNWFlZTBiMjg3ODdhZDg4YTVkNThmYjA1Y2NmMjI5MThkYWE1MTZlYWQ4NWE2YmY0ZmUwNjg=", 20L));
		add(new Pair<>("NjM2MTFiNTcyNGUwOTE4NTRlNzk5MjZmZDExZTQ4NmJmZDBmOTkwNDI3MjFjM2IzNDE3N2Y4MTg2MzljMTlk", 10L));
		add(new Pair<>("ODNlMDYyMWI0NWQzYTMyNmQyMzYyOTNjZDhlYTQ5YWU3NGQ1MmU1NmZjOGQxZDEzM2U3ZmM4YmNmMmE1OTg4", 9L));
		add(new Pair<>("NmUxNmE3YWUxODZjM2NmZWFjMzY0ZWFjMGU4M2QzNTI4NzQxYzNkZDllZjgyNzcwODBlMDNkZWFiYzcxNA==", 4L));
		add(new Pair<>("MjBlYzNhODBlZDM1YmQ5YmViN2QyMGNiNzVmMWVjZDViOGFiMGQ1NzZmMWRiNjk5ZjdkZWYxMzEzMWZiYzU=", 2L));
		add(new Pair<>("YjAzYmFkY2M5ZmI5NjZjODdlMGRjMTMzMmQ3MzViMmI1ODdjMjYwMmQzNWZlY2I0NGJhNmVkOTRjZWI0", 1L));
		add(new Pair<>("NDM5YzNkZjdhNjI4YWY4ZDc1MWVjY2ExOTc2NDJjZGMxYTA3YzMwZTMyODliMmQzMjYxZjdhNjVjZjM5NWI=", 39L));
		add(new Pair<>("YjAzYmFkY2M5ZmI5NjZjODdlMGRjMTMzMmQ3MzViMmI1ODdjMjYwMmQzNWZlY2I0NGJhNmVkOTRjZWI0", 2L));
		add(new Pair<>("MjBlYzNhODBlZDM1YmQ5YmViN2QyMGNiNzVmMWVjZDViOGFiMGQ1NzZmMWRiNjk5ZjdkZWYxMzEzMWZiYzU=", 1L));
		add(new Pair<>("NmUxNmE3YWUxODZjM2NmZWFjMzY0ZWFjMGU4M2QzNTI4NzQxYzNkZDllZjgyNzcwODBlMDNkZWFiYzcxNA==", 3L));
		add(new Pair<>("ODNlMDYyMWI0NWQzYTMyNmQyMzYyOTNjZDhlYTQ5YWU3NGQ1MmU1NmZjOGQxZDEzM2U3ZmM4YmNmMmE1OTg4", 30L));
		add(new Pair<>("NmUxNmE3YWUxODZjM2NmZWFjMzY0ZWFjMGU4M2QzNTI4NzQxYzNkZDllZjgyNzcwODBlMDNkZWFiYzcxNA==", 3L));
		add(new Pair<>("MjBlYzNhODBlZDM1YmQ5YmViN2QyMGNiNzVmMWVjZDViOGFiMGQ1NzZmMWRiNjk5ZjdkZWYxMzEzMWZiYzU=", 2L));
		add(new Pair<>("YjAzYmFkY2M5ZmI5NjZjODdlMGRjMTMzMmQ3MzViMmI1ODdjMjYwMmQzNWZlY2I0NGJhNmVkOTRjZWI0", 1L));
		add(new Pair<>("NDM5YzNkZjdhNjI4YWY4ZDc1MWVjY2ExOTc2NDJjZGMxYTA3YzMwZTMyODliMmQzMjYxZjdhNjVjZjM5NWI=", 85L));
	}}),
	DIZZY("NGM0NmVlNzZmZDllOTQ3ZTM3ODlmYWMzNDgyMTZhYjk4YzI0MjEyNjhmYWZhZjNlYjI5ZWM5NDljMGI4MjE2OQ==", new ArrayList<>() {{
		add(new Pair<>("NGM0NmVlNzZmZDllOTQ3ZTM3ODlmYWMzNDgyMTZhYjk4YzI0MjEyNjhmYWZhZjNlYjI5ZWM5NDljMGI4MjE2OQ==", 41L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 1L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 1L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 1L));
		add(new Pair<>("NGM0NmVlNzZmZDllOTQ3ZTM3ODlmYWMzNDgyMTZhYjk4YzI0MjEyNjhmYWZhZjNlYjI5ZWM5NDljMGI4MjE2OQ==", 41L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 0L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 1L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 0L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 1L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NGM0NmVlNzZmZDllOTQ3ZTM3ODlmYWMzNDgyMTZhYjk4YzI0MjEyNjhmYWZhZjNlYjI5ZWM5NDljMGI4MjE2OQ==", 40L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 0L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 0L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 1L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 0L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NGM0NmVlNzZmZDllOTQ3ZTM3ODlmYWMzNDgyMTZhYjk4YzI0MjEyNjhmYWZhZjNlYjI5ZWM5NDljMGI4MjE2OQ==", 41L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 0L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 0L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 1L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 0L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 0L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 1L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NDE2ZjNkY2U5NzdkOGI3OTdlMWU0NzZmNWFiOTM2MTllZDJmMmIyMWE0OWFjOTM3NDMxNDBjZjY3YTA4OA==", 1L));
		add(new Pair<>("NjE4MDNhNzEzMmZiZTU5ZTY1MDYwZGRlYzYyNjNkNjc0YTFkYTZkMjM4Y2UwYWRhMTQwZTY3OTliMjg1NTlk", 1L));
		add(new Pair<>("ZDg5MmZjNTViMjM0YjNiNTM1NjNjZDQ4Zjk4YzI2ZThlM2Y3ZTVhZTM1MjNiNmVlZDg5YjI2MmVjZjFjNWQ1", 0L));
		add(new Pair<>("YmExNTFhNTVlYmE3MzRmMWM2NTFiYmM3ZTcxN2NjOGE3ZmY1NTc1ZDY4MDRmMTM3ZDFjZDIxNjEzMTQ5ODlm", 2L));
		add(new Pair<>("NGM0NmVlNzZmZDllOTQ3ZTM3ODlmYWMzNDgyMTZhYjk4YzI0MjEyNjhmYWZhZjNlYjI5ZWM5NDljMGI4MjE2OQ==", 14L));
	}}),
	RELAX("MmY3ZTZjMDc5ZWZhNjljYjNhMjNkZDNiMTQ3NjQzYzdjYjVlNWM5MTI5Yjc0YWYwY2FiNDdiMDRmMzU1YQ==", new ArrayList<>() {{
		add(new Pair<>("OTI3ZWJiZjVjMjUzNWZlNmI1Y2VmOGI4YTdlMWU3MDY3YTM5ZWQyMWJhNTQ3ZjgzZmNlNDQ3MjE4NGQ4MGM3", 20L));
		add(new Pair<>("ZmQyZGM0ZGI3ODAyOTQ5MTk1MTczMDY5NjRkNjVlYTA3OGI0N2I4MjNmZGE1NjI4YmU0OGI2YWU2MWM=", 3L));
		add(new Pair<>("ZTc0NGU2MWI0NmE1Zjc0OWNjYWEyYmY4MTMyOTgxYjg5ODYyMzQzNTlmOWEyOTI0ZjU0N2VjMDExMWU0Mzc1", 3L));
		add(new Pair<>("MzNiYzM4YzZlOTU3NDE5ZjZhNDg0ZmZlYjQ3MzhkMWU1Y2VmOWQ5MGNmOGIyODc5NjRmNjgzMTMxOTFkOGM=", 4L));
		add(new Pair<>("NGM5YjliMzFmMTE1ZTNjYjYzOWM2NGU4M2FiZmRlMzE1OTdkMTVlYjcxOTlkMTRjY2JiYTZjNzgyMjFmMWYxOQ==", 4L));
		add(new Pair<>("YjZkNjU4MWVlMGVjOTNjYTlkNWY0YWZiZjZlMjhmNWE5NTgyYTg5NmNjY2NiOWU3YzE3ZTY0MTllNTk3ZTI3", 10L));
		add(new Pair<>("ZTA4ODc2YTQ5YjFhYmJhZDE0OTcyNGJlM2VhZTM1YWE2MzA1YzUyOWUzODRjMTE4YmEzODFhODFlMmRmNTll", 3L));
		add(new Pair<>("OTI3ZWJiZjVjMjUzNWZlNmI1Y2VmOGI4YTdlMWU3MDY3YTM5ZWQyMWJhNTQ3ZjgzZmNlNDQ3MjE4NGQ4MGM3", 2L));
		add(new Pair<>("ZTA4ODc2YTQ5YjFhYmJhZDE0OTcyNGJlM2VhZTM1YWE2MzA1YzUyOWUzODRjMTE4YmEzODFhODFlMmRmNTll", 4L));
		add(new Pair<>("OTI3ZWJiZjVjMjUzNWZlNmI1Y2VmOGI4YTdlMWU3MDY3YTM5ZWQyMWJhNTQ3ZjgzZmNlNDQ3MjE4NGQ4MGM3", 1L));
		add(new Pair<>("ZTA4ODc2YTQ5YjFhYmJhZDE0OTcyNGJlM2VhZTM1YWE2MzA1YzUyOWUzODRjMTE4YmEzODFhODFlMmRmNTll", 3L));
		add(new Pair<>("N2U2M2EwYzJkNjMxODg0ZTlmN2E0MDJhZTkzODEzOTg4MTMxYzdiMDc5OGMxNWY0YzdjNDc1NjI1ZmUwNTgyZA==", 4L));
		add(new Pair<>("NzYyYzNhNjI2NTQxODk3N2E1NjRmYTkzNzZmYjViMWE4N2Y5ZjhiODA1MmM2M2EyZDUxODE3NjkxZTQyMjNh", 4L));
		add(new Pair<>("M2I3ODkxNzQ1Njg2NTExZDUzOWFhZDkyYmEzMDM3YjAyNWFiYWRkYjllMmVlNmU1OWM3OTk3N2E3MTdhNGY5Yg==", 4L));
		add(new Pair<>("ODFiMTNiMmRjYjk0ZGNmYzMwZWM3Y2U3NzA1ZTZlMzhhNjQ1N2M0M2ViOWY4YWUxYzQzYmE1MjQxNjNmYTQ2OQ==", 4L));
		add(new Pair<>("MmY3ZTZjMDc5ZWZhNjljYjNhMjNkZDNiMTQ3NjQzYzdjYjVlNWM5MTI5Yjc0YWYwY2FiNDdiMDRmMzU1YQ==", 3L));
		add(new Pair<>("M2I3ODkxNzQ1Njg2NTExZDUzOWFhZDkyYmEzMDM3YjAyNWFiYWRkYjllMmVlNmU1OWM3OTk3N2E3MTdhNGY5Yg==", 4L));
		add(new Pair<>("ODFiMTNiMmRjYjk0ZGNmYzMwZWM3Y2U3NzA1ZTZlMzhhNjQ1N2M0M2ViOWY4YWUxYzQzYmE1MjQxNjNmYTQ2OQ==", 3L));
		add(new Pair<>("MmY3ZTZjMDc5ZWZhNjljYjNhMjNkZDNiMTQ3NjQzYzdjYjVlNWM5MTI5Yjc0YWYwY2FiNDdiMDRmMzU1YQ==", 4L));
		add(new Pair<>("M2I3ODkxNzQ1Njg2NTExZDUzOWFhZDkyYmEzMDM3YjAyNWFiYWRkYjllMmVlNmU1OWM3OTk3N2E3MTdhNGY5Yg==", 4L));
		add(new Pair<>("ODFiMTNiMmRjYjk0ZGNmYzMwZWM3Y2U3NzA1ZTZlMzhhNjQ1N2M0M2ViOWY4YWUxYzQzYmE1MjQxNjNmYTQ2OQ==", 3L));
		add(new Pair<>("MmY3ZTZjMDc5ZWZhNjljYjNhMjNkZDNiMTQ3NjQzYzdjYjVlNWM5MTI5Yjc0YWYwY2FiNDdiMDRmMzU1YQ==", 3L));
		add(new Pair<>("M2I3ODkxNzQ1Njg2NTExZDUzOWFhZDkyYmEzMDM3YjAyNWFiYWRkYjllMmVlNmU1OWM3OTk3N2E3MTdhNGY5Yg==", 4L));
		add(new Pair<>("ODFiMTNiMmRjYjk0ZGNmYzMwZWM3Y2U3NzA1ZTZlMzhhNjQ1N2M0M2ViOWY4YWUxYzQzYmE1MjQxNjNmYTQ2OQ==", 3L));
		add(new Pair<>("MmY3ZTZjMDc5ZWZhNjljYjNhMjNkZDNiMTQ3NjQzYzdjYjVlNWM5MTI5Yjc0YWYwY2FiNDdiMDRmMzU1YQ==", 42L));
	}}),
	SPICY("OTYzYmE5Zjg4ZmE1ZjUzNTlkNWNkOTRlOWRmOGNlZWJmZGNkNDM1NWQ1YmZiNWZlNjczMjUxZWRlMGU3ZjYzZA==", new ArrayList<>() {{
		add(new Pair<>("OTI3ZWJiZjVjMjUzNWZlNmI1Y2VmOGI4YTdlMWU3MDY3YTM5ZWQyMWJhNTQ3ZjgzZmNlNDQ3MjE4NGQ4MGM3", 19L));
		add(new Pair<>("NTg0ZjllZTY4NWVjNjU0ZWE1OTQxZDc4OTgzODc4NWQzMjE0ZTIzNjE1M2ZhMmU0ODIyODc2YmNmZWY4OQ==", 8L));
		add(new Pair<>("ZTM0ZGFkNmM5ZWFiMGJhZjlmOWQ5YjBmNmJlNmUxOTkzNmIzYTFlMjBmYzNlMjE3Yjg4NWVhZGViMzE4", 4L));
		add(new Pair<>("OTYzYmE5Zjg4ZmE1ZjUzNTlkNWNkOTRlOWRmOGNlZWJmZGNkNDM1NWQ1YmZiNWZlNjczMjUxZWRlMGU3ZjYzZA==", 30L));
		add(new Pair<>("OGU1OGFjOTkxMTQ1NjExMDM3Nzc5OWNkZmQ3NWE1ZjRmZDczMWEzOGJkMjlhYjM5ODg3OTQzYWFhMTM5", 3L));
		add(new Pair<>("MjFmOTZiZmM5MDVjNDY4OTY5OGMwOWNkMmNiYjgxODgyNTE0NmMxYmM2MTg0OTQwMzNlODA3N2NiOWE3MA==", 4L));
		add(new Pair<>("MWU1Njc1NTU3ZGVkZWVlZGQ0NTk5ZmQwYzBiMmVhZTdkOGRlZmJmYzYxM2YzMjFmNTEwYzc0YzY2MmEzYTY=", 3L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 5L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 1L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 5L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 2L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 4L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 2L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 4L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 2L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 4L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 2L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 5L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 1L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 5L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 1L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 4L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 2L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 5L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 1L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 5L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 1L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 5L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 2L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 4L));
		add(new Pair<>("ODgxMWVjMzYxOGRmYzA3NTgxOGFmOGE3ZmRhNTJlZTU2YzBiYjIwM2U0ZDI3ODIxZTE3ODZmMmFmNTViOWQ=", 2L));
		add(new Pair<>("NDlmMDQ4MmNhNmJhNTk5ZmJlZDQ2YTFlN2JiMzMyNDU5YWMxMzIxYmI1Y2MyZGM5YmYyYTJiYTdmNjFiOA==", 1L));
	}}),
	SUNTAN("ODAzODg5ZTQ0YjU1NDY1YWJmZjVjZWRjNWI4NmQzYmRhMzQ2YmM3MGM5YmY4Yjk3ZmNmNzkzOTQ4ZjM3OWMx", new ArrayList<>() {{
		add(new Pair<>("MmQyMTc1ZWJlOWFlMGUxYTY1OGQ5YWY4MmRhY2ZiODM2OTA1MmQ4MTIxZDRlYTM4ODY3MzhhMWNjYTU=", 20L));
		add(new Pair<>("ZTM4YWRkZTNhYTRkZjJjZjhhNTIxNjY0M2QzZjZmOTIxMzNlMTU5OWQ1MGIyZWY0MWNlZmM4MWYxZWVjMTdj", 10L));
		add(new Pair<>("Mjg1Yzc4OWIxYmFmZWI2Mjc0ZDVjMzMxNGUwMzMzY2NmNmFiOTJkNzMxMmVmMjE0Zjg5NzkzYzk1OWQyNQ==", 3L));
		add(new Pair<>("N2VmNTc1NjI5YTI2ODlkNjNhM2EzZTkxYmQzNDJlYzNmNzhiNGYzOTc2ODdjMDgzM2JmNmQ2NGJmMjZkMTJlOA==", 16L));
		add(new Pair<>("NTZmMGM2YTZmNTUyNWQwODc2NzczNzY4ZTJhN2Y2YmQ0MzYwOGQ4YjE1ZjBlODc4MGY2NGQ1MTJmMjA=", 10L));
		add(new Pair<>("ZjAzZWM2MjFlZjIzMTc1ZWU0ZWVjYzVkMWQ5MjIyYjllMjdjYTg3NThiZWRlNTA0ZTNmYTNjMGFjMTUzMmJk", 10L));
		add(new Pair<>("Nzc4YWIzNzgxZGZlOTZlNTE5YjE3NGU0N2VmZGJjNjg4MTcxNWQ3YWU4Y2E0MWExZDhhZTYyMGY0Nzc5ZDI=", 9L));
		add(new Pair<>("OGRkZGEzZGY5ZmRlMzAyMDhjYWQxYTMwODYzNGM5NWY5NWM5YjQ4YTQyNzg0MmFkYzljOGNjZmVjNjI2YjRm", 15L));
		add(new Pair<>("NzM2NWM2NjZlN2Q5ODA0Mzk3ZTc2ZGUzNTVlZTJlNjhkNGM5NjliNWZmN2MwYWI2YWY3N2JkN2M3ZTI2Ng==", 4L));
		add(new Pair<>("ODAzODg5ZTQ0YjU1NDY1YWJmZjVjZWRjNWI4NmQzYmRhMzQ2YmM3MGM5YmY4Yjk3ZmNmNzkzOTQ4ZjM3OWMx", 9L));
		add(new Pair<>("MTVlMTEyMmM4MzdhODdjZTE4ZDUxZTc5Nzk4M2RhNmFkMzg0NzkzZmRkOWY3NzI1Mzc2M2FlOWI2ZDlhMQ==", 0L));
		add(new Pair<>("ODAzODg5ZTQ0YjU1NDY1YWJmZjVjZWRjNWI4NmQzYmRhMzQ2YmM3MGM5YmY4Yjk3ZmNmNzkzOTQ4ZjM3OWMx", 20L));
		add(new Pair<>("MTVlMTEyMmM4MzdhODdjZTE4ZDUxZTc5Nzk4M2RhNmFkMzg0NzkzZmRkOWY3NzI1Mzc2M2FlOWI2ZDlhMQ==", 0L));
		add(new Pair<>("ODAzODg5ZTQ0YjU1NDY1YWJmZjVjZWRjNWI4NmQzYmRhMzQ2YmM3MGM5YmY4Yjk3ZmNmNzkzOTQ4ZjM3OWMx", 67L));
	}}),
	MOUSTACHE("ZmFkMGIxZGI3NTZiMzNjODEyNTRkOWNkYjFjNzE5MmM0ZmU2NGJkZGFjMjBkZWY1ZjQyZWIyNTQ1MjczMg==", new ArrayList<>() {{
		add(new Pair<>("ZjM3ZWJjNjBmMGZmODBlNDZkMTI2ODMyOGRkZWMxNDBiZmMxMzZlZGE5OWRmZWE1ZTc3NWVmOTM4NWE3Y2MyOA==", 19L));
		add(new Pair<>("ZTNjZWMyNjg0M2VjOGMzMjk0N2M4ZGMzNGY1ZGFkODM0MDMzYzA1ZmVkOTc4OWJjYTMyMzE3OTYxZTU4NGUxMA==", 4L));
		add(new Pair<>("N2Q3ZGUzMmQyOTgwYjIzNmMxNDVmNjEwOWFhMDI5NjgzYTQ2ODk2YzgyMmU3N2I4NDM4ZTNkOTc1OWNmNmM=", 4L));
		add(new Pair<>("NGRkZGYwOWRhMTk1Y2UwNDEzMjliNjVkNjYwODc2OWZkZTAxOWE4NjNhODM1OTc4MjQzMmE4YzRhNDFkZWVh", 4L));
		add(new Pair<>("ZTU5MjI5OWY2YzNhZmI4MzQ5ZGMyYTcxZmM1ZjE5OTljNDFmMTliNmQ4OWZmMjkwY2Y2ZTg4NDE4NDQwOWFhMw==", 4L));
		add(new Pair<>("NmQzNjYyODdjYzM5ODQ0YWYxNDJjODczNTU0ODk2OGMwODEyNWM3N2M3ODRiOWRhZWM0OTUwMzk1Zjk3NDE=", 19L));
		add(new Pair<>("ZDVkYjg4M2E3MWU2ZDZjMGJjZjMwYTg1NmU0YjZlNjkxMjg2Yjg2MjY4MzBhYTFkMTc4ZmE3ZGU3OWU1MA==", 1L));
		add(new Pair<>("NmQzNjYyODdjYzM5ODQ0YWYxNDJjODczNTU0ODk2OGMwODEyNWM3N2M3ODRiOWRhZWM0OTUwMzk1Zjk3NDE=", 2L));
		add(new Pair<>("ZDVkYjg4M2E3MWU2ZDZjMGJjZjMwYTg1NmU0YjZlNjkxMjg2Yjg2MjY4MzBhYTFkMTc4ZmE3ZGU3OWU1MA==", 1L));
		add(new Pair<>("NmQzNjYyODdjYzM5ODQ0YWYxNDJjODczNTU0ODk2OGMwODEyNWM3N2M3ODRiOWRhZWM0OTUwMzk1Zjk3NDE=", 19L));
		add(new Pair<>("ZTU5MjI5OWY2YzNhZmI4MzQ5ZGMyYTcxZmM1ZjE5OTljNDFmMTliNmQ4OWZmMjkwY2Y2ZTg4NDE4NDQwOWFhMw==", 5L));
		add(new Pair<>("NGRkZGYwOWRhMTk1Y2UwNDEzMjliNjVkNjYwODc2OWZkZTAxOWE4NjNhODM1OTc4MjQzMmE4YzRhNDFkZWVh", 4L));
		add(new Pair<>("N2Q3ZGUzMmQyOTgwYjIzNmMxNDVmNjEwOWFhMDI5NjgzYTQ2ODk2YzgyMmU3N2I4NDM4ZTNkOTc1OWNmNmM=", 3L));
		add(new Pair<>("ZTNjZWMyNjg0M2VjOGMzMjk0N2M4ZGMzNGY1ZGFkODM0MDMzYzA1ZmVkOTc4OWJjYTMyMzE3OTYxZTU4NGUxMA==", 22L));
		add(new Pair<>("N2Q3ZGUzMmQyOTgwYjIzNmMxNDVmNjEwOWFhMDI5NjgzYTQ2ODk2YzgyMmU3N2I4NDM4ZTNkOTc1OWNmNmM=", 2L));
		add(new Pair<>("M2Y1ZTgzNDJhNjQ0ZmQ5YWVkYTA1NGEwNGQyYjkxMmE2NjI1NzA3MjI4ODlmZGU3OTAxOTkzOWNiYmJkNmNl", 3L));
		add(new Pair<>("MmVkMzgwYzQ1MjdlYjI3YTRkMzhmZmZjZTc1NGFmZTNmNDg0ZjRiNGM3OTQzNDc0MTMxZjY4NWI2YTNmNjk=", 4L));
		add(new Pair<>("ZWZiYzc0MmViZjY2ZjNlZGIwZTEyNzU1ZWU1NWJmZGJlZDE1M2Y1ZWM2NzU3NGUyMWVkODFkMjlhZDU0NTFh", 6L));
		add(new Pair<>("Y2I3Yjk4NzNjOWQzZTJjMmIyYjYxZDhlMzQ4NzY5ZGQwZmVmZWQ4OTNjN2JkNGZjMTMzNjMyMGMxODhiMWM1", 19L));
		add(new Pair<>("MzFiYmIyNmRlMzQ4Y2M2NWRiZjdiZTRlODBkOTY4OGY4ZTVhZGI5MTkxMWI5YTU0ZGM3NzUxN2JhNzMx", 1L));
		add(new Pair<>("Y2I3Yjk4NzNjOWQzZTJjMmIyYjYxZDhlMzQ4NzY5ZGQwZmVmZWQ4OTNjN2JkNGZjMTMzNjMyMGMxODhiMWM1", 0L));
		add(new Pair<>("MzFiYmIyNmRlMzQ4Y2M2NWRiZjdiZTRlODBkOTY4OGY4ZTVhZGI5MTkxMWI5YTU0ZGM3NzUxN2JhNzMx", 1L));
		add(new Pair<>("Y2I3Yjk4NzNjOWQzZTJjMmIyYjYxZDhlMzQ4NzY5ZGQwZmVmZWQ4OTNjN2JkNGZjMTMzNjMyMGMxODhiMWM1", 23L));
		add(new Pair<>("MmVkMzgwYzQ1MjdlYjI3YTRkMzhmZmZjZTc1NGFmZTNmNDg0ZjRiNGM3OTQzNDc0MTMxZjY4NWI2YTNmNjk=", 0L));
		add(new Pair<>("M2Y1ZTgzNDJhNjQ0ZmQ5YWVkYTA1NGEwNGQyYjkxMmE2NjI1NzA3MjI4ODlmZGU3OTAxOTkzOWNiYmJkNmNl", 5L));
		add(new Pair<>("N2Q3ZGUzMmQyOTgwYjIzNmMxNDVmNjEwOWFhMDI5NjgzYTQ2ODk2YzgyMmU3N2I4NDM4ZTNkOTc1OWNmNmM=", 5L));
		add(new Pair<>("ZjM3ZWJjNjBmMGZmODBlNDZkMTI2ODMyOGRkZWMxNDBiZmMxMzZlZGE5OWRmZWE1ZTc3NWVmOTM4NWE3Y2MyOA==", 34L));
		add(new Pair<>("N2Q3ZGUzMmQyOTgwYjIzNmMxNDVmNjEwOWFhMDI5NjgzYTQ2ODk2YzgyMmU3N2I4NDM4ZTNkOTc1OWNmNmM=", 8L));
		add(new Pair<>("M2Y1ZTgzNDJhNjQ0ZmQ5YWVkYTA1NGEwNGQyYjkxMmE2NjI1NzA3MjI4ODlmZGU3OTAxOTkzOWNiYmJkNmNl", 7L));
		add(new Pair<>("MmVkMzgwYzQ1MjdlYjI3YTRkMzhmZmZjZTc1NGFmZTNmNDg0ZjRiNGM3OTQzNDc0MTMxZjY4NWI2YTNmNjk=", 0L));
		add(new Pair<>("Y2I3Yjk4NzNjOWQzZTJjMmIyYjYxZDhlMzQ4NzY5ZGQwZmVmZWQ4OTNjN2JkNGZjMTMzNjMyMGMxODhiMWM1", 5L));
		add(new Pair<>("MzhmZmVlNmQ4MGJkZTA4YjU2YjZhYjJmNmMwNmI1ZGQxMmM1YWZjZDJlYTg5NmU4NmYyZTVkNmRhYzc1YzJk", 3L));
		add(new Pair<>("MTg2ODVlOTQ0Y2ZmNGIyZDY3MmI2OTQzMTNiYjZiZmEyNWFkYWZiOTYwNTM0NmFmNTQzZDhiZTc4OTZiZThj", 5L));
		add(new Pair<>("ZmFkMGIxZGI3NTZiMzNjODEyNTRkOWNkYjFjNzE5MmM0ZmU2NGJkZGFjMjBkZWY1ZjQyZWIyNTQ1MjczMg==", 3L));
		add(new Pair<>("YTA3ZmY0YzM5ODZlM2Q0OWVmMTQyMTg0MDc3ZGYzNDE1OGRhNWYzNzNiMDU5MTJiYmU2Mzg3MDI3NzI1YjI4", 17L));
		add(new Pair<>("YzY4YTlmNzNlZTFhNzExN2MwZjIzODExMzgzZjg2NDgxNGU0ODlhMzdkOTQ2NDExMzI4MzQyOTZjZTFhNmY=", 1L));
		add(new Pair<>("YTA3ZmY0YzM5ODZlM2Q0OWVmMTQyMTg0MDc3ZGYzNDE1OGRhNWYzNzNiMDU5MTJiYmU2Mzg3MDI3NzI1YjI4", 1L));
		add(new Pair<>("YzY4YTlmNzNlZTFhNzExN2MwZjIzODExMzgzZjg2NDgxNGU0ODlhMzdkOTQ2NDExMzI4MzQyOTZjZTFhNmY=", 1L));
		add(new Pair<>("YTA3ZmY0YzM5ODZlM2Q0OWVmMTQyMTg0MDc3ZGYzNDE1OGRhNWYzNzNiMDU5MTJiYmU2Mzg3MDI3NzI1YjI4", 131L));
	}}),
	FACEMELTER("MzQ4MWE4YjZlYWM2NzcxZTQ3YjRkM2ExNzE3NjAxMTEzNTZkOGUxODU0OTg5ZDVmN2M5ZTMzMDZjMjQyNw==", new ArrayList<>() {{
		add(new Pair<>("NGM0NmVlNzZmZDllOTQ3ZTM3ODlmYWMzNDgyMTZhYjk4YzI0MjEyNjhmYWZhZjNlYjI5ZWM5NDljMGI4MjE2OQ==", 44L));
		add(new Pair<>("OTA2ZGMwYzNlYmJmNjEyNWQzMDk1NjRlZDhlZTE2N2Y4NzBhMjgwODFkMzIyNDI1NTI4YTkyODIzNDJmYTQ=", 18L));
		add(new Pair<>("OGViNjgxYjU5MWNlNmEyOTY3MTg4MzNlNjk0MjFlYmUzNjllYjE3YzI0NDk5MjFjY2IyNDk2OGEyZGExOGYx", 21L));
		add(new Pair<>("OWUzMzFkZGNjOTU4ZGQ2NGJiYTk5MmU3NWM3MzBlMjk0M2FmMzdmMmRmMmZhZjdkNGQ4YmE1OWYyODVkNzM=", 19L));
		add(new Pair<>("ZjAzZTZhNTE2NTc5NjU5OTNmMjhmN2VhM2Q5OTk3YzhlMDdkYWU0ODlkZmIxNDlhODVjYzI4YWE4NWQxMzk5ZQ==", 19L));
		add(new Pair<>("MzQ4MWE4YjZlYWM2NzcxZTQ3YjRkM2ExNzE3NjAxMTEzNTZkOGUxODU0OTg5ZDVmN2M5ZTMzMDZjMjQyNw==", 19L));
		add(new Pair<>("MzQ4MWE4YjZlYWM2NzcxZTQ3YjRkM2ExNzE3NjAxMTEzNTZkOGUxODU0OTg5ZDVmN2M5ZTMzMDZjMjQyNw==", 20L));
		add(new Pair<>("MzQ4MWE4YjZlYWM2NzcxZTQ3YjRkM2ExNzE3NjAxMTEzNTZkOGUxODU0OTg5ZDVmN2M5ZTMzMDZjMjQyNw==", 136L));
	}}),
	PRESENT("ZjM1NzgzYmVmNTk4Y2JlZmVkMmUzYjNiOWJhNDZkNDg0YWNjY2U4ODQ4N2Q2NGFhM2M0ZDdjZmM4ODEyZTY=", new ArrayList<>() {{
		add(new Pair<>("NTA1ZWIyNzkzYmFlMTQ1MGUwOTQ2MGIxZGJhZmMwNmQ5NGZjZDgyYjdiYTZiYWEzM2QwNDNiMmI5Y2Y4OTk=", 39L));
		add(new Pair<>("OGIxZTYyZjljYTMxMDFiYTZiNzk5ZmI3OWIzYWMzOWRhNjcyODIxZDNmZmVjYjliNWM3MjE1ZWU0OGUwNzI=", 1L));
		add(new Pair<>("NTA3NTExYmQzZDNkOGUzNzRkYzY3NGEyY2YxNDY5Mzg5NDkxOTk2NjQxNmRlMmY4YzVkNDFhNmQxNmY1M2Rj", 3L));
		add(new Pair<>("YTM4NmNmZDY4Zjg0ZDA3OGZmMTM4MGE4YjFhY2ZhNzliZWRkOGU4MTZlZmM2MjJhYWI0MjFlNGMyYWM4MTRkZQ==", 1L));
		add(new Pair<>("YmI4OWRhNjQwZGJhMjE2Zjk0NDRiN2Q0NWU5OTlhZDVkZTA2YWM1ZmVhMWMwN2VjN2I5MzgzZDQ1YjlhMDk3", 1L));
		add(new Pair<>("MmI0NmM3OGMzYzNjMmFkNTFhMjViYTdlYzhhOTE3ZDExN2I5ZTQzZDZiNTQ5ZTEzOTViZmE1NWZjNDQ=", 2L));
		add(new Pair<>("ZDEyOGY2YzJkOWVmNmM5ZmY5Mzc5M2M5YTM0Y2I2MmJkZjY1NDc3OGQ1YjZmYWVjNmM2OGJiNTJiN2Q0Nzc=", 2L));
		add(new Pair<>("MzkxYzVjODlkZDk5YzQxYjE4NDRiM2I2NTFmOTdmZGE5MTNiNjYxODRkMTcwZTZmYjczZWIzYjEwOGFlNzdj", 3L));
		add(new Pair<>("Y2EyMWVlYjUyNjQzY2ZlYjI2YWQ2M2JkNTE3Njg5OTUxY2MyOTQxMzg4ZDFkZDllZjE1MWUyODExYg==", 1L));
		add(new Pair<>("NDE4YmZkZjdiMTdhN2Y5YTFkMTMzNmYxNWFiMGNmNTI4N2E1ZTg3OTgxOWNjZjIyNzE1ZjJhZTcyNWM2ZGE=", 3L));
		add(new Pair<>("ZjM1NzgzYmVmNTk4Y2JlZmVkMmUzYjNiOWJhNDZkNDg0YWNjY2U4ODQ4N2Q2NGFhM2M0ZDdjZmM4ODEyZTY=", 3L));
		add(new Pair<>("MjRmNDM5YzFjYzc0YTY0MTY2ODhkMzQ4MTExZjNlY2RlNjUyNzMxODhhOTZhMDFkM2Y5NGEwMThmOGJhZjdk", 1L));
		add(new Pair<>("Y2U2NjE5ZjZjYTg4YWQzMzE2ODIwOTZkMjMxYzg5ZWI1NjNkMjVhNDk3MTMwYTE5OWFjYzg2YzBiY2E=", 1L));
		add(new Pair<>("MjM1NGJhMDc0MzEzN2VlZDU0YjYwYjkxZWU1NGZjZjhmNGY0ZDNiMmNlY2M2MTY0NWY2ZTFhMjY3MTViNA==", 2L));
		add(new Pair<>("YjhiM2QzMjNmYTllNDkxMjc5MzA0NDNhYTMxZTczMjNhODJmMjA5NDk4YzBmMDc2MjU5ZTQzMzc4ZjE0MTg4", 2L));
		add(new Pair<>("MzU3ZjEwNTA0MzM0N2I4Y2JlMWVlZjQ0MzdjYTc1YzkzN2ZlMjcyMWJjOWJiZDI4YzgxYzgzNGM3M2E1Yw==", 2L));
		add(new Pair<>("YWE5MTdmNDQzMTM0ZmRjNmI1NWJhM2UwZmJjYjI4ODViYjM3YzZmN2NkZmY1ZjI5Yjc0YmY4YTgwZTdmZg==", 1L));
		add(new Pair<>("NWM1ZWQwMzEzMTYzMWYzMDE0ZmNiMWY0MzVjMjE5NWJiOTZiYzJhNDY0OTYzN2E5MjdlNGU0YTMzYWQ=", 3L));
		add(new Pair<>("YjcwNmU0MTc1ZWRiZjU1NjY5YTk0Njg3ZDFmY2I5MWU1NDVhNDQ3ZGQ0NmMwZjNmNGUxOTlhMDlhOTM=", 1L));
		add(new Pair<>("NTMzNGYxZWEyYTc2NGFhZDM1NjZiNGJjYWVlNjE2NTUyN2FiM2MxZTMxYmI3YTJiNGMxZTVjZTRhYWU3MmQ=", 3L));
		add(new Pair<>("MTI5MGM2ODkyN2U4NzkyNzYzZWUzNmU4NDE0ODBhMWJhZDEyYTcxMTE3ODEzZTk5YjI1ZDkyNWVkODE4M2Y1", 2L));
		add(new Pair<>("NTFhNGRmZmQ0NWMyOGE0YTdjMmVlZmMxZjBkMWYwNmRhMDQwMmU3ZDk4N2U1NTE5NTE3N2M2MThiNDllZjg4", 3L));
		add(new Pair<>("ZjBjZGI2OGUwM2Q0NWFlNGE2MWFiYzEzZDk3ZTdlOThhZmE1ZTc5MjA3Y2QzYTc3Mjg0Y2ZlMjAyZDZk", 3L));
		add(new Pair<>("YzJjNzgyMjBkNzY4MTNkOTk3Y2Q1MjEzYmYyOWRiNGFlODRlMTI2ZmNiYTQ4YzkyOTQyMTE3ODhhMTVlNzk3", 1L));
		add(new Pair<>("ZThjZTVhOGYwZDM2MzgxOGRjYjVjMzFjOWEyNmExYmVhOTZlNzc4MmM0YTk2NzFmN2E0ODEyNmU1Y2UwNWE=", 1L));
		add(new Pair<>("OWFlNDM4YmRlMzNjZDkzYjIyODU5NjZlZTE1ZGE2M2IyOGEyNWFjMmU0ZDVmYzA1ZWVjN2QzYzNmODZjYTUz", 41L));
		add(new Pair<>("OWYzYWMwNzhkMWNlZTQ1ZWIzNGE2MWQyNGJkNDMyZGE3MDQ1NDJhZDMzOTE4MjE1M2I5NzhiN2JmNzlmYzFlMw==", 1L));
		add(new Pair<>("ZTI3MmU4ZmJkNDk1Yzg3MjM3NjQyOGQzMWMwZDMzOTJlMjJkYTQxYzNkMjhiMThmODRmYTNhZWRlNzg3", 5L));
		add(new Pair<>("OWFlNDM4YmRlMzNjZDkzYjIyODU5NjZlZTE1ZGE2M2IyOGEyNWFjMmU0ZDVmYzA1ZWVjN2QzYzNmODZjYTUz", 16L));
	}}),
	;

	private static final String URL = "https://textures.minecraft.net/texture/";

	private final String menuTexture;
	private final List<Pair<String, Long>> frameTextures;
	@Getter
	private List<Pair<ItemStack, Long>> frames;

	EmojiHat(String menuTexture, List<Pair<String, Long>> frames) {
		this.menuTexture = menuTexture;
		this.frameTextures = frames;

		Runnable load = () -> this.frames = new ArrayList<>() {{
			for (Pair<String, Long> frame : frames)
				add(new Pair<>(getSkull(frame.getFirst()), frame.getSecond()));
		}};

		Tasks.async(() -> new Timer("    EmojiHat." + name(), load));
	}

	public static void init() {
		// static init
	}

	public ItemBuilder getDisplayItem() {
		ItemStack skull = getSkull(menuTexture);
		return new ItemBuilder(skull).name(camelCase(this));
	}

	public void run(Player player) {
		int wait = 0;
		for (Pair<ItemStack, Long> frame : frames) {
			final ItemStack item = frame.getFirst();
			final long ticks = frame.getSecond();

			for (int i = 0; i <= ticks; i++)
				Tasks.wait(wait++, () -> packet(player, item));
		}

		Tasks.wait(wait + 1, () -> packet(player, player.getInventory().getItem(EquipmentSlot.HEAD)));
	}

	private void packet(Player player, ItemStack item) {
		PacketUtils.setSlot(player, List.of(player), item, EnumItemSlot.HEAD);
	}

	public List<ItemStack> getFrameItems() {
		return frames.stream().map(Pair::getFirst).distinct().toList();
	}

	private final static Map<String, ItemStack> loadedSkulls = new ConcurrentHashMap<>();

	private ItemStack getSkull(String base64) {
		return loadedSkulls.computeIfAbsent(base64, $ -> SkullCreator.itemFromUrl(URL + decode(base64)));
	}

	@NotNull
	private String decode(@NotNull String base64) {
		return new String(Base64.getDecoder().decode(base64));
	}
}
