package gg.projecteden.nexus.features.events.y2021.halloween21.models;

import gg.projecteden.nexus.features.resourcepack.models.ItemModelType;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum PumpkinType {
	AXOLOTL(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_AXOLOTL),
	BEE(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_BEE),
	CAT(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_CAT),
	CREEPER(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_CREEPER),
	CREEPY(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_CREEPY),
	FACE(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_FACE),
	FLAT(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_FLAT),
	GHOST(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_GHOST),
	GRINCH(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_GRINCH),
	HAPPY(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_HAPPY),
	HEART(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_HEART),
	HEROBRINE(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_HEROBRINE),
	OBSERVER(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_OBSERVER),
	SANS(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_SANS),
	SILLY(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_SILLY),
	SLIME(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_SLIME),
	STEVE(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_STEVE),
	SUNGLASSES(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_SUNGLASSES),
	TOOTHY(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_TOOTHY),
	UPSIDEDOWN(ItemModelType.EXCLUSIVE_HAT_PUMPKINS_UPSIDEDOWN),
	;

	private final ItemModelType itemModelType;
}
