package gg.projecteden.nexus.features.chat.translator;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum Language {
	UNKNOWN("Unknown"),
	AF("Afrikaans"),
	AM("Amharic"),
	AR("Arabic"),
	AZ("Azerbaijani"),
	BA("Bashkir"),
	BE("Belarusian"),
	BG("Bulgarian"),
	BN("Bengali"),
	BS("Bosnian"),
	CA("Catalan"),
	CEB("Cebuano"),
	CS("Czech"),
	CY("Welsh"),
	DA("Danish"),
	DE("German"),
	EL("Greek"),
	EN("English"),
	EO("Esperanto"),
	ES("Spanish"),
	ET("Estonian"),
	EU("Basque"),
	FA("Persian"),
	FI("Finnish"),
	FR("French"),
	GA("Irish"),
	GD("Scottish Gaelic"),
	GL("Galician"),
	GU("Gujarati"),
	HE("Hebrew"),
	HI("Hindi"),
	HR("Croatian"),
	HT("Haitian"),
	HU("Hungarian"),
	HY("Armenian"),
	ID("Indonesian"),
	IS("Icelandic"),
	IT("Italian"),
	JA("Japanese"),
	JV("Javanese"),
	KA("Georgian"),
	KK("Kazakh"),
	KM("Khmer"),
	KN("Kannada"),
	KO("Korean"),
	KY("Kyrgyz"),
	LA("Latin"),
	LB("Luxembourgish"),
	LO("Lao"),
	LT("Lithuanian"),
	LV("Latvian"),
	MG("Malagasy"),
	MHR("Mari"),
	MI("Maori"),
	MK("Macedonian"),
	ML("Malayalam"),
	MN("Mongolian"),
	MR("Marathi"),
	MRJ("Hill Mari"),
	MS("Malay"),
	MT("Maltese"),
	MY("Burmese"),
	NE("Nepali"),
	NL("Dutch"),
	NO("Norwegian"),
	PA("Punjabi"),
	PAP("Papiamento"),
	PL("Polish"),
	PT("Portuguese"),
	RO("Romanian"),
	RU("Russian"),
	SI("Sinhalese"),
	SK("Slovak"),
	SL("Slovenian"),
	SQ("Albanian"),
	ST("Serbian"),
	SU("Sundanese"),
	SV("Swedish"),
	SW("Swahili"),
	TA("Tamil"),
	TE("Telugu"),
	TG("Tajik"),
	TH("Thai"),
	TL("Tagalog"),
	TR("Turkish"),
	TT("Tatar"),
	UDM("Udmurt"),
	UK("Ukrainian"),
	UR("Urdu"),
	UZ("Uzbek"),
	VI("Vietnamese"),
	XH("Xhosa"),
	YI("Yiddish"),
	ZH("Chinese");

	@Getter
	private final String name;
}
